### ISSUE TITLE
Craftbukkit v1_9_R2 isn't supported.

### ISSUE THREAD

**Issue by Exceptionflug** [5zig/The-5zig-Mod-API-2.0#4]
Hey 5zig,

during startup, the following error appears in the console:

[10:54:08] [Server thread/INFO]: [The5zigMod] Enabling The5zigMod v2.3
[10:54:08] [Server thread/INFO]: [The5zigMod] Trying to setup Hooks for CraftBukkit v1_9_R2
[10:54:08] [Server thread/WARN]: java.lang.ClassNotFoundException: eu.the5zig.mod.server.util.protocol.BufferUtils_v1_9_R2
[10:54:08] [Server thread/WARN]: 	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
[10:54:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
[10:54:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
[10:54:08] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
[10:54:08] [Server thread/WARN]: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
[10:54:08] [Server thread/WARN]: 	at java.lang.Class.forName0(Native Method)
[10:54:08] [Server thread/WARN]: 	at java.lang.Class.forName(Class.java:264)
[10:54:08] [Server thread/WARN]: 	at eu.the5zig.mod.server.The5zigMod.setupHooks(The5zigMod.java:68)
[10:54:08] [Server thread/WARN]: 	at eu.the5zig.mod.server.The5zigMod.onEnable(The5zigMod.java:39)
[10:54:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:292)
[10:54:08] [Server thread/WARN]: 	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
[10:54:08] [Server thread/WARN]: 	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
[10:54:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.loadPlugin(CraftServer.java:362)
[10:54:08] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_9_R2.CraftServer.enablePlugins(CraftServer.java:322)
[10:54:08] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.t(MinecraftServer.java:416)
[10:54:08] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.l(MinecraftServer.java:381)
[10:54:08] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.a(MinecraftServer.java:336)
[10:54:08] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.DedicatedServer.init(DedicatedServer.java:268)
[10:54:08] [Server thread/WARN]: 	at net.minecraft.server.v1_9_R2.MinecraftServer.run(MinecraftServer.java:532)
[10:54:08] [Server thread/WARN]: 	at java.lang.Thread.run(Thread.java:745)
[10:54:08] [Server thread/ERROR]: [The5zigMod] Could not find support for this CraftBukkit version

It seems that v1_9_R2 isn't supported. I only found v1_9_R1 in the javadocs. Please add the v1_9_R2 support. After that you can say, that the api is supporting all minecraft versions from 1.8 to 1.11 :)

**Comment by 5zig** [comment]
Thanks, version 2.3.2 of the server API is now compatible with Bukkit 1_9_R2 as well. :)
